"""One-shot setup for a fresh object store: `python -m app.storage.init`.

Garage starts with no layout, bucket or key. This runs the admin API calls
that create them, then sets CORS through the S3 API. Every step is safe to
repeat. The key id and secret are generated by the `secrets` service, so the
repo holds none; Garage only imports them.
"""

import json
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

import boto3
from botocore.config import Config

from app.config import get_settings

ADMIN_URL = "http://objectstore:3903"
ADMIN_TOKEN_FILE = Path("/run/inspection-secrets/objectstore/admin_token")
KEY_NAME = "inspection-api"
# One node, one zone. Capacity is a placement weight here, not a quota.
NODE_ZONE = "local"
NODE_CAPACITY_BYTES = 10 * 1024**3
# A browser POSTs the file to a presigned URL and shows thumbnails fetched with GET.
# Nothing else is asked of the store from a page, so nothing else is allowed.
CORS_METHODS = ["GET", "POST"]
CORS_HEADERS = ["content-type"]
CORS_MAX_AGE_SECONDS = 600


def _admin(path: str, body: dict | None = None, *, query: str = "") -> dict | list:
    token = ADMIN_TOKEN_FILE.read_text().strip()
    request = urllib.request.Request(  # noqa: S310 (fixed internal http URL)
        f"{ADMIN_URL}{path}{query}",
        data=None if body is None else json.dumps(body).encode(),
        method="GET" if body is None else "POST",
        headers={"Authorization": f"Bearer {token}", "Content-Type": "application/json"},
    )
    with urllib.request.urlopen(request, timeout=10) as response:  # noqa: S310
        payload = response.read()
    return json.loads(payload) if payload else {}


def _wait_for_admin_api() -> None:
    for _ in range(60):
        try:
            _admin("/v2/GetClusterStatus")
            return
        except (urllib.error.URLError, OSError):
            time.sleep(1)
    raise SystemExit("objectstore-init: admin API did not become reachable")


def _ensure_layout() -> None:
    status = _admin("/v2/GetClusterStatus")
    node_id = status["nodes"][0]["id"]
    if status["nodes"][0]["role"] is not None:
        return
    _admin(
        "/v2/UpdateClusterLayout",
        {
            "roles": [
                {"id": node_id, "zone": NODE_ZONE, "capacity": NODE_CAPACITY_BYTES, "tags": []}
            ]
        },
    )
    version = _admin("/v2/GetClusterLayout")["version"]
    _admin("/v2/ApplyClusterLayout", {"version": version + 1})


def _ensure_key(access_key_id: str, secret_access_key: str) -> None:
    keys = _admin("/v2/ListKeys")
    if any(key["id"] == access_key_id for key in keys):
        return
    _admin(
        "/v2/ImportKey",
        {"name": KEY_NAME, "accessKeyId": access_key_id, "secretAccessKey": secret_access_key},
    )


def _ensure_bucket(name: str) -> str:
    buckets = _admin("/v2/ListBuckets")
    existing = next((b for b in buckets if name in b.get("globalAliases", [])), None)
    if existing:
        return existing["id"]
    return _admin("/v2/CreateBucket", {"globalAlias": name})["id"]


def _set_key_permissions(bucket_id: str, access_key_id: str, *, owner: bool) -> None:
    """Read and write always; `owner` (needed to set CORS) only while setting it up."""
    body = {"bucketId": bucket_id, "accessKeyId": access_key_id}
    _admin("/v2/AllowBucketKey", {**body, "permissions": {"read": True, "write": True}})
    route = "/v2/AllowBucketKey" if owner else "/v2/DenyBucketKey"
    _admin(route, {**body, "permissions": {"owner": True}})


def _ensure_cors(access_key_id: str, secret_access_key: str) -> None:
    settings = get_settings()
    client = boto3.client(
        "s3",
        endpoint_url=settings.s3_endpoint,
        region_name=settings.s3_region,
        aws_access_key_id=access_key_id,
        aws_secret_access_key=secret_access_key,
        config=Config(
            s3={"addressing_style": "path"},
            request_checksum_calculation="when_required",
            response_checksum_validation="when_required",
        ),
    )
    client.put_bucket_cors(
        Bucket=settings.s3_bucket,
        CORSConfiguration={
            "CORSRules": [
                {
                    "AllowedOrigins": sorted(settings.origins),
                    "AllowedMethods": CORS_METHODS,
                    "AllowedHeaders": CORS_HEADERS,
                    "MaxAgeSeconds": CORS_MAX_AGE_SECONDS,
                }
            ]
        },
    )


def main() -> None:
    settings = get_settings()
    access_key_id = settings.s3_access_key_id_file.read_text().strip()
    secret_access_key = settings.s3_secret_access_key_file.read_text().strip()
    _wait_for_admin_api()
    _ensure_layout()
    _ensure_key(access_key_id, secret_access_key)
    bucket_id = _ensure_bucket(settings.s3_bucket)
    # The API's key may read and write objects but not reconfigure the bucket.
    # It holds owner rights only for the CORS call below.
    _set_key_permissions(bucket_id, access_key_id, owner=True)
    try:
        _ensure_cors(access_key_id, secret_access_key)
    finally:
        _set_key_permissions(bucket_id, access_key_id, owner=False)
    print("objectstore-init: ready", file=sys.stdout)


if __name__ == "__main__":
    main()
